import Defs.lean
import Reto_1.lean
import Reto_2.lean
import Reto_3.lean
import Reto_4.lean
import Reto_5.lean
import Reto_6.lean
import Reto_7.lean
import Reto_8.lean
import Reto_9.lean
import Reto_10.lean
import Reto_11.lean
import Reto_12.lean
import Reto_13.lean
import Reto_14.lean
import Reto_15.lean
import Reto_16.lean
import Reto_17.lean
import Reto_18.lean
import Reto_19.lean
import Reto_20.lean
import Reto_21.lean
import Reto_22.lean
